<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-R71JSJF" failures="4" tests="4" name="Test" time="48.339" errors="0" timestamp="2023-04-14T15:50:58 IST">
  <testcase classname="TC_01.DataProvider" name="Data" time="11.828">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at TC_01.DataProvider.Data(DataProvider.java:73)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- Data -->
  <testcase classname="TC_01.DataProvider" name="Data" time="10.851">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at TC_01.DataProvider.Data(DataProvider.java:73)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- Data -->
  <testcase classname="TC_01.DataProvider" name="Data" time="10.424">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at TC_01.DataProvider.Data(DataProvider.java:73)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- Data -->
  <testcase classname="TC_01.DataProvider" name="Data" time="10.398">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at TC_01.DataProvider.Data(DataProvider.java:73)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- Data -->
</testsuite> <!-- Test -->
